LoseMenu:
                                               
.wYOU dd Object.MENU, 40 * Drawing.NORMAL, 120 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG, .wYOU1, 'Y', 'O', 'U', 0 
.wYOU1 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>                              
.wYOU2 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wYOU3 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>

.wLOST dd Object.MENU, 100 * Drawing.NORMAL, 120 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG, .wLOST1, 'L', 'O', 'S', 'T', 0
.wLOST1 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>                              
.wLOST2 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wLOST3 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wLOST4 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>

.wA dd Object.MENU, 178 * Drawing.NORMAL, 120 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG, .wA1, 'A', 0 
.wA1 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>                              

.wLIFE dd Object.MENU, 202 * Drawing.NORMAL, 120 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG, .wLIFE1, 'L', 'I', 'F', 'E', 0
.wLIFE1 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>                              
.wLIFE2 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wLIFE3 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wLIFE4 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>

.wSCORE dd Object.MENU, 80 * Drawing.NORMAL, 100 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG, .wSCORE1, 'S', 'C', 'O', 'R', 'E', 0 
.wSCORE1 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>                              
.wSCORE2 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>
.wSCORE3 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>
.wSCORE4 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>  
.wSCORE5 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>

.nSCORE dd Object.MENU, 155 * Drawing.NORMAL, 100 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG, .nSCORE1, '0', '0', '0', '0', '0', 0 
.nSCORE1 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>                              
.nSCORE2 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>
.nSCORE3 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>
.nSCORE4 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>  
.nSCORE5 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>

.wBEST dd Object.MENU, 80 * Drawing.NORMAL, 80 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG, .wBEST1, 'B', 'E', 'S', 'T', 0
.wBEST1 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>                              
.wBEST2 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>
.wBEST3 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>
.wBEST4 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>  
.wBEST5 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>

.nBEST dd Object.MENU, 155 * Drawing.NORMAL, 80 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG, .nBEST1, '0', '0', '0', '0', '0', 0 
.nBEST1 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>                              
.nBEST2 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>
.nBEST3 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>
.nBEST4 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>  
.nBEST5 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>

.star1 Star\
<<<Object.MENU, 82 * Drawing.BIG, 39 * Drawing.BIG, STAR_WIDTH * Drawing.BIG, STAR_HEIGHT * Drawing.BIG>>,\ 
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidStarTexture>>,\
1, level1.levelStatistics.stars

.star2 Star\
<<<Object.MENU, 102 * Drawing.BIG, 39 * Drawing.BIG, STAR_WIDTH * Drawing.BIG, STAR_HEIGHT * Drawing.BIG>>,\ 
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidStarTexture>>,\
2, level1.levelStatistics.stars

.star3 Star\
<<<Object.MENU, 122 * Drawing.BIG, 39 * Drawing.BIG, STAR_WIDTH * Drawing.BIG, STAR_HEIGHT * Drawing.BIG>>,\ 
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidStarTexture>>,\
3, level1.levelStatistics.stars

.background1 MenuObjectWithDrawing\
<<Object.MENU, 84 * Drawing.BIG, 20 * Drawing.BIG, MENU_WIDTH * Drawing.BIG, MENU_HEIGHT * Drawing.BIG>>,\
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, screenButtonTexture>

.menuButton Button\
<<<Object.MENU, 84 * Drawing.BIG, 20 * Drawing.BIG, MENU_WIDTH * Drawing.BIG, MENU_HEIGHT * Drawing.BIG>>,\
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, menuTexture>>,\
TRUE, Button.Menu, levelsMenu

.background2 MenuObjectWithDrawing\
<<Object.MENU, 115 * Drawing.BIG, 20 * Drawing.BIG, MENU_WIDTH * Drawing.BIG, MENU_HEIGHT * Drawing.BIG>>,\
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, screenButtonTexture>
                                   
.restartButton Button\
<<<Object.MENU, 115 * Drawing.BIG, 20 * Drawing.BIG, RESTART_WIDTH * Drawing.BIG, RESTART_HEIGHT * Drawing.BIG>>,\
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, restartTexture>>,\
FALSE, Button.GameRestart, 0


.menuObjects                    dd .menuObjectsLength / 4 - 1

.menuObjectsLength              = $ - .menuObjects

.menuObjectsWithDrawing         dd .menuObjectsWithDrawingLength / 4 - 1,\
                                   activeButtonElement1, activeButtonElement2, activeButtonElement3, activeButtonElement4,\
                                   .wYOU1, .wYOU2, .wYOU3, .wLOST1, .wLOST2, .wLOST3, .wLOST4, .wA1, .wLIFE1, .wLIFE2, .wLIFE3, .wLIFE4,\
                                   .wSCORE1, .wSCORE2, .wSCORE3, .wSCORE4, .wSCORE5, .nSCORE1, .nSCORE2, .nSCORE3, .nSCORE4, .nSCORE5,\
                                   .wBEST1, .wBEST2, .wBEST3, .wBEST4, .nBEST1, .nBEST2, .nBEST3, .nBEST4, .nBEST5,\
                                   .star1, .star2, .star3,\
                                   .background1, .menuButton, .background2, .restartButton
.menuObjectsWithDrawingLength   = $ - .menuObjectsWithDrawing

.menuObjectsWithAnimation       dd .menuObjectsWithAnimationLength / 4 - 1,\
                                   activeButtonElement1, activeButtonElement2, activeButtonElement3, activeButtonElement4
.menuObjectsWithAnimationLength = $ - .menuObjectsWithAnimation

.buttons			                  dd .buttonsLength / 4 - 3,\
                                   0, .menuButton, .restartButton, 0
.buttonsLength			            = $ - .buttons

.stars                          dd .starsLength / 4 - 1,\
                                   .star1, .star2, .star3
.starsLength                    = $ - .stars

.strings                        dd .stringsLength / 4 - 1,\
                                   .wYOU, .wLOST, .wA, .wLIFE, .wSCORE, .nSCORE, .wBEST, .nBEST
.stringsLength                  = $ - .strings
                                                                                                                                                                                       
loseMenu Menu <173, 181, 224>, <LoseMenu.menuObjects, LoseMenu.menuObjectsWithDrawing, LoseMenu.menuObjectsWithAnimation, LoseMenu.buttons, LoseMenu.stars, LoseMenu.strings>