;Location1----------------------------------------------------------------------
owlAnimations dd 1000, 0, 0, deathOwlFrames, 120, 0, 0, owlFrames

venusFlycatcherAnimations dd 1000, 0, 0, deathVenusFlycatcherFrames, 120, 0, 0, venusFlycatcherFrames

beeAnimations dd 1000, 0, 0, deathBeeFrames, 120, 0, 0, beeFrames

;Location2----------------------------------------------------------------------

;Location3----------------------------------------------------------------------

;Location4----------------------------------------------------------------------

;Location5----------------------------------------------------------------------