;General------------------------------------------------------------------------

NO_ANIMATION = 0

;Player-------------------------------------------------------------------------
standingPlayerFrames dd 3, standingPlayerTexture1, standingPlayerTexture2, standingPlayerTexture3
runPlayerFrames      dd 6, runPlayerTexture1, runPlayerTexture2, runPlayerTexture3, runPlayerTexture4, runPlayerTexture5, runPlayerTexture6

;Bonuses------------------------------------------------------------------------
floppyFrames dd 2, floppyTexture1, floppyTexture2
heartFrames  dd 2, heartTexture1, heartTexture2

;Blocks-------------------------------------------------------------------------
luckFrames dd 4, luckTexture1, luckTexture2, luckTexture3, luckTexture4


;Location1----------------------------------------------------------------------

;Blocks-------------------------------------------------------------------------

;Mobs---------------------------------------------------------------------------
owlFrames      dd 6, owlTexture1, owlTexture2, owlTexture3, owlTexture4, owlTexture5, owlTexture6
deathOwlFrames dd 1, deathOwlTexture

venusFlycatcherFrames      dd 2, venusFlycatcherTexture1, venusFlycatcherTexture2
deathVenusFlycatcherFrames dd 1, deathVenusFlycatcherTexture

beeFrames      dd 2, beeTexture1, beeTexture2
deathBeeFrames dd 1, deathBeeTexture

;Decorations--------------------------------------------------------------------

;Background---------------------------------------------------------------------