;General------------------------------------------------------------------------

NO_DRAWING = 0

;Player-------------------------------------------------------------------------
include 'General/Player/standingPlayer1.inc'
include 'General/Player/standingPlayer2.inc'
include 'General/Player/standingPlayer3.inc'

include 'General/Player/runPlayer1.inc'
include 'General/Player/runPlayer2.inc'
include 'General/Player/runPlayer3.inc'
include 'General/Player/runPlayer4.inc'
include 'General/Player/runPlayer5.inc'
include 'General/Player/runPlayer6.inc'

include 'General/Player/upJumpPlayer.inc'

include 'General/Player/downJumpPlayer.inc'

;Bonuses------------------------------------------------------------------------
include 'General/Bonuses/floppy1.inc'
include 'General/Bonuses/floppy2.inc'

include 'General/Bonuses/heart1.inc'
include 'General/Bonuses/heart2.inc'

;Blocks-------------------------------------------------------------------------
include 'General/Blocks/shadow.inc'

include 'General/Blocks/dirt.inc'

include 'General/Blocks/brick.inc'

include 'General/Blocks/luck1.inc'
include 'General/Blocks/luck2.inc'
include 'General/Blocks/luck3.inc'
include 'General/Blocks/luck4.inc'

include 'General/Blocks/block.inc'

include 'General/Blocks/blueBlock.inc'

include 'General/Blocks/greenBlock.inc'

include 'General/Blocks/pinkBlock.inc'

include 'General/Blocks/yellowBlock.inc'

include 'General/Blocks/bottomPipe.inc'
include 'General/Blocks/topPipe.inc'


;Location1----------------------------------------------------------------------

;Blocks-------------------------------------------------------------------------
include 'Location1/Blocks/grass.inc'

;Mobs---------------------------------------------------------------------------
include 'Location1/Mobs/owl1.inc'
include 'Location1/Mobs/owl2.inc'
include 'Location1/Mobs/owl3.inc'
include 'Location1/Mobs/owl4.inc'
include 'Location1/Mobs/owl5.inc'
include 'Location1/Mobs/owl6.inc'

include 'Location1/Mobs/deathOwl.inc'

include 'Location1/Mobs/venusFlycatcher1.inc'
include 'Location1/Mobs/venusFlycatcher2.inc'

include 'Location1/Mobs/deathVenusFlycatcher.inc'

include 'Location1/Mobs/bee1.inc'
include 'Location1/Mobs/bee2.inc'

include 'Location1/Mobs/deathBee.inc'

;Decorations--------------------------------------------------------------------
include 'Location1/Decorations/bush.inc'

include 'Location1/Decorations/palm.inc'

include 'Location1/Decorations/flower.inc'

;Background---------------------------------------------------------------------