include 'Object.asm'

include 'Animation/Animation.asm'
include 'Array/Array.asm'
include 'Color/Color.asm'
include 'Drawing/Drawing.asm'
include 'Normalize/Normalize.asm'
include 'Number/Number.asm'
include 'Screen/Screen.asm'
include 'String/String.asm'
include 'Timer/Timer.asm'
include 'WindowProcFunctions/WindowProcFunctions.asm'

include '../Frames/Frames.inc'
include '../Music/Music.inc'
include '../Texture/Texture.inc'

include '../Game/Game.asm'
include '../Menu/Menu.asm'                 