;General------------------------------------------------------------------------
;Mobs---------------------------------------------------------------------------
beeAnimations dd\
TRUE, 0, 0, 0, deadBeeFrames,\
FALSE, 0, 120, 0, beeFrames

coreAnimations dd\ 
TRUE, 0, 0, 0, voidFrames,\
FALSE, 0, 10, 0, coreFrames

snailAnimations dd\ 
TRUE, 0, 0, 0, deadSnailFrames,\ 
TRUE, 0, 0, 0, deadSnailFrames,\ 
TRUE, 0, 0, 0, deadSnailFrames,\ 
FALSE, 0, 100, 0, snailFrames

venusFlycatcherAnimations dd\
TRUE, 0, 0, 0, deadVenusFlycatcherFrames,\
FALSE, 0, 120, 0, venusFlycatcherFrames

;Player-------------------------------------------------------------------------
invulnerablePlayerAnimations dd\
FALSE, 0, 200, 0, invulnerableStandingPlayerFrames,\
FALSE, 0, 200, 0, invulnerableRunningPlayerFrames,\
FALSE, 0, 200, 0, invulnerableUpJumpingPlayerFrames,\
FALSE, 0, 200, 0, invulnerableDownJumpingPlayerFrames,\
FALSE, 0, 200, 0, invulnerableDyingPlayerFrames

playerAnimations dd\
FALSE, 0, 200, 0, standingPlayerFrames,\
FALSE, 0, 100, 0, runningPlayerFrames,\
TRUE, 0, 0, 0, upJumpingPlayerFrames,\
TRUE, 0, 0, 0, downJumpingPlayerFrames,\
TRUE, 0, 0, 0, dyingPlayerFrames

playerBulletAnimations dd\
TRUE, 0, 100, 0, deadPlayerBulletFrames,\
FALSE, 0, 120, 0, playerBulletFrames

;Location1----------------------------------------------------------------------
;Mobs---------------------------------------------------------------------------
honeyAnimations dd\ 
TRUE, 0, 0, 0, deadHoneyFrames,\ 
FALSE, 0, 100, 0, honeyFrames

owlAnimations dd\
TRUE, 0, 0, 0, deadOwlFrames,\
FALSE, 0, 100, 0, owlFrames

;Location2----------------------------------------------------------------------
;Mobs---------------------------------------------------------------------------
coconutAnimations dd\
TRUE, 0, 0, 0, deadCoconutFrames,\
FALSE, 0, 100, 0, coconutFrames

sigmaAnimations dd\
TRUE, 0, 0, 0, deadSigmaFrames,\
FALSE, 0, 100, 0, nedoSigmaFrames,\
FALSE, 0, 100, 0, sigmaFrames

spiderAnimations dd\
TRUE, 0, 0, 0, deadSpiderFrames,\ 
FALSE, 0, 100, 0, spiderFrames