include '../Animations/Animations.inc'

include 'GameObject.asm'
include 'Entity/Entity.asm'

include 'Bonus/Bonus.asm'
include 'BrickWithBreakTimer/BrickWithBreakTimer.asm'
include 'Bullet/Bullet.asm'
include 'Enemy/Enemy.asm'
include 'Enemy/EnemyWithTimer.asm'
include 'Enemy/EnemyWithBullets.asm'
include 'Enemy/EnemyWithReverseTimer.asm'
include 'Enemy/EnemyWithStopTimer.asm'
include 'Luck/Luck.asm'
include 'Player/Player.asm'
include 'Enemy/Snail.asm'
include 'Teleport/Teleport.asm'

include '../Levels/Levels.inc'

include 'Collide/Collide.asm'
include 'Move/Move.asm'
include 'Result/Result.asm'
include 'Statistic/Statistic.asm'

include 'KeyDown.asm'
include 'KeyUp.asm'
include 'Paint.asm'
include 'Timer.asm'