WinMenu:
                                               
.wLEVEL String <Object.MENU, 25 * Drawing.NORMAL, 120 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG>, <'L', 'E', 'V', 'E', 'L', 0, 0, 0, 0, 0>, .wLEVEL1
.wLEVEL1 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>                              
.wLEVEL2 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wLEVEL3 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wLEVEL4 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>  
.wLEVEL5 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>

.wCOMPLETED String <Object.MENU, 125 * Drawing.NORMAL, 120 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.HUGE - Drawing.HUGE, A_HEIGHT * Drawing.HUGE>, <'C', 'O', 'M', 'P', 'L', 'E', 'T', 'E', 'D', 0>, .wCOMPLETED1
.wCOMPLETED1 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>                              
.wCOMPLETED2 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wCOMPLETED3 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wCOMPLETED4 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>  
.wCOMPLETED5 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wCOMPLETED6 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wCOMPLETED7 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>
.wCOMPLETED8 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>  
.wCOMPLETED9 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * (Drawing.BIG + 2), A_HEIGHT * (Drawing.BIG + 2)>>, <(Drawing.BIG + 2), Drawing.RIGHT, Drawing.UP, voidTexture>

.wSCORE String <Object.MENU, 80 * Drawing.NORMAL, 100 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG>, <'S', 'C', 'O', 'R', 'E', 0, 0, 0, 0, 0>, .wSCORE1
.wSCORE1 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>                              
.wSCORE2 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>
.wSCORE3 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>
.wSCORE4 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>  
.wSCORE5 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>

.nSCORE Number <Object.MENU, 155 * Drawing.NORMAL, 100 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG>, 0, <0, 0, 0, 0, 0>, .nSCORE1
.nSCORE1 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>                              
.nSCORE2 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>
.nSCORE3 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>
.nSCORE4 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>  
.nSCORE5 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>

.wBEST String <Object.MENU, 80 * Drawing.NORMAL, 80 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG>, <'B', 'E', 'S', 'T', 0, 0, 0, 0, 0, 0>, .wBEST1
.wBEST1 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>                              
.wBEST2 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>
.wBEST3 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>
.wBEST4 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>  
.wBEST5 MenuObjectWithDrawing <<Object.MENU, 0, 0, A_WIDTH * Drawing.BIG, A_HEIGHT * Drawing.BIG>>, <Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidTexture>

.nBEST Number <Object.MENU, 155 * Drawing.NORMAL, 80 * Drawing.NORMAL, 4 * (A_WIDTH + 1) * Drawing.BIG - Drawing.BIG, A_HEIGHT * Drawing.BIG>, 0, <0, 0, 0, 0, 0>, .nBEST1
.nBEST1 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>                              
.nBEST2 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>
.nBEST3 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>
.nBEST4 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>  
.nBEST5 MenuObjectWithDrawing <<Object.MENU, 0, 0, ZERO_WIDTH * Drawing.HUGE, ZERO_HEIGHT * Drawing.HUGE>>, <Drawing.HUGE, Drawing.RIGHT, Drawing.UP, voidTexture>

.star1 Star\
<<<Object.MENU, 82 * Drawing.BIG, 39 * Drawing.BIG, STAR_WIDTH * Drawing.BIG, STAR_HEIGHT * Drawing.BIG>>,\ 
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidStarTexture>>,\
1, level1

.star2 Star\
<<<Object.MENU, 102 * Drawing.BIG, 39 * Drawing.BIG, STAR_WIDTH * Drawing.BIG, STAR_HEIGHT * Drawing.BIG>>,\ 
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidStarTexture>>,\
2, level1

.star3 Star\
<<<Object.MENU, 122 * Drawing.BIG, 39 * Drawing.BIG, STAR_WIDTH * Drawing.BIG, STAR_HEIGHT * Drawing.BIG>>,\ 
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, voidStarTexture>>,\
3, level1

.background1 MenuObjectWithDrawing\
<<Object.MENU, 70 * Drawing.BIG, 20 * Drawing.BIG, MENU_WIDTH * Drawing.BIG, MENU_HEIGHT * Drawing.BIG>>,\
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, screenButtonTexture>

.menuButton Button\
<<<Object.MENU, 70 * Drawing.BIG, 20 * Drawing.BIG, MENU_WIDTH * Drawing.BIG, MENU_HEIGHT * Drawing.BIG>>,\
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, menuTexture>>,\
FALSE, Button.Menu, levelsMenu

.background2 MenuObjectWithDrawing\
<<Object.MENU, 100 * Drawing.BIG, 20 * Drawing.BIG, MENU_WIDTH * Drawing.BIG, MENU_HEIGHT * Drawing.BIG>>,\
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, screenButtonTexture>
                                   
.restartButton Button\
<<<Object.MENU, 100 * Drawing.BIG, 20 * Drawing.BIG, RESTART_WIDTH * Drawing.BIG, RESTART_HEIGHT * Drawing.BIG>>,\
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, restartTexture>>,\
FALSE, Button.GameRestart, 0

.background3 MenuObjectWithDrawing\
<<Object.MENU, 130 * Drawing.BIG, 20 * Drawing.BIG, MENU_WIDTH * Drawing.BIG, MENU_HEIGHT * Drawing.BIG>>,\
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, screenButtonTexture>

.nextButton Button\
<<<Object.MENU, 130 * Drawing.BIG, 20 * Drawing.BIG, CONTINUE_WIDTH * Drawing.BIG, CONTINUE_HEIGHT * Drawing.BIG>>,\
<Drawing.BIG, Drawing.RIGHT, Drawing.UP, nextTexture>>,\
TRUE, Button.GameNext, 0
                                   



.menuObjects                    dd .menuObjectsLength / 4 - 1

.menuObjectsLength              = $ - .menuObjects

.menuObjectsWithDrawing         dd .menuObjectsWithDrawingLength / 4 - 1,\
                                   activeButtonElement1, activeButtonElement2, activeButtonElement3, activeButtonElement4,\
                                   .wLEVEL1, .wLEVEL2, .wLEVEL3, .wLEVEL4, .wLEVEL5, .wCOMPLETED1, .wCOMPLETED2, .wCOMPLETED3, .wCOMPLETED4, .wCOMPLETED5, .wCOMPLETED6, .wCOMPLETED7, .wCOMPLETED8, .wCOMPLETED9,\
                                   .wSCORE1, .wSCORE2, .wSCORE3, .wSCORE4, .wSCORE5, .nSCORE1, .nSCORE2, .nSCORE3, .nSCORE4, .nSCORE5,\
                                   .wBEST1, .wBEST2, .wBEST3, .wBEST4, .nBEST1, .nBEST2, .nBEST3, .nBEST4, .nBEST5,\
                                   .star1, .star2, .star3,\
                                   .background1, .menuButton, .background2, .restartButton, .background3, .nextButton
.menuObjectsWithDrawingLength   = $ - .menuObjectsWithDrawing

.menuObjectsWithAnimation       dd .menuObjectsWithAnimationLength / 4 - 1,\
                                   activeButtonElement1, activeButtonElement2, activeButtonElement3, activeButtonElement4
.menuObjectsWithAnimationLength = $ - .menuObjectsWithAnimation

.buttons			                  dd .buttonsLength / 4 - 3,\
                                   0, .menuButton, .restartButton, .nextButton, 0
.buttonsLength			            = $ - .buttons

.stars                          dd .starsLength / 4 - 1,\
                                   .star1, .star2, .star3
.starsLength                    = $ - .stars

.words                          dd .wordsLength / 4 - 1,\
                                   .wLEVEL, .wCOMPLETED, .wSCORE, .wBEST
.wordsLength                    = $ - .words

.numbers                        dd .numbersLength / 4 - 1,\
                                   .nSCORE, .nBEST 
.numbersLength                  = $ - .numbers
                                                                                                                                                                                       
winMenu Menu <173, 181, 224>, <WinMenu.menuObjects, WinMenu.menuObjectsWithDrawing, WinMenu.menuObjectsWithAnimation, WinMenu.buttons, WinMenu.stars, WinMenu.words, WinMenu.numbers>